// Code generated by scripts/abi.ts. DO NOT EDIT.
package contractabi

import (
	_ "embed"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"strings"
)

func parse(source string) abi.ABI {
	parsed, err := abi.JSON(strings.NewReader(source))
	if err != nil {
		panic(err)
	}
	return parsed
}

//go:embed ERC20.json
var erc20JSON string

var ERC20 = parse(erc20JSON)

//go:embed Executor.json
var executorJSON string

var Executor = parse(executorJSON)

//go:embed PancakeQuoterV2.json
var pancakeQuoterV2JSON string

var PancakeQuoterV2 = parse(pancakeQuoterV2JSON)

//go:embed PancakeV3Factory.json
var pancakeV3FactoryJSON string

var PancakeV3Factory = parse(pancakeV3FactoryJSON)

//go:embed PancakeV3Router.json
var pancakeV3RouterJSON string

var PancakeV3Router = parse(pancakeV3RouterJSON)

//go:embed UniswapPeripheryState.json
var uniswapPeripheryStateJSON string

var UniswapPeripheryState = parse(uniswapPeripheryStateJSON)

//go:embed UniswapQuoterV2.json
var uniswapQuoterV2JSON string

var UniswapQuoterV2 = parse(uniswapQuoterV2JSON)

//go:embed UniswapRouter02.json
var uniswapRouter02JSON string

var UniswapRouter02 = parse(uniswapRouter02JSON)

//go:embed UniswapV3Factory.json
var uniswapV3FactoryJSON string

var UniswapV3Factory = parse(uniswapV3FactoryJSON)
