import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const goDirectory = "services/quote-engine/internal/contractabi";
const tsDirectory = "generated/abi";
const goNames = new Set([
  "ERC20",
  "Executor",
  "UniswapRouter02",
  "UniswapV3Factory",
  "UniswapQuoterV2",
  "UniswapPeripheryState",
  "PancakeV3Router",
  "PancakeV3Factory",
  "PancakeQuoterV2",
]);

// Only reviewed local canonical inputs are read. No network or runtime ABI source.
export async function abiFiles(directory = root) {
  const records = JSON.parse(
    await readFile(join(directory, "contracts/abi/provenance.json"), "utf8"),
  ) as Array<{ name: string; abiSha256: string }>;
  const names = records.map((record) => record.name);
  if (
    new Set(names).size !== names.length ||
    names.some((name) => !/^[A-Z][A-Za-z0-9]+$/.test(name))
  )
    throw new Error("Invalid canonical ABI names.");
  const actual = (await readdir(join(directory, "contracts/abi")))
    .filter((name) => name.endsWith(".json") && name !== "provenance.json")
    .sort();
  if (
    actual.join() !==
    names
      .map((name) => `${name}.json`)
      .sort()
      .join()
  )
    throw new Error("Canonical ABI inventory differs from provenance.");
  const files = new Map<string, string>();
  let ts =
    "// Generated by scripts/abi.ts. Do not edit.\nimport type { Abi } from 'viem';\n\n";
  let go = `// Code generated by scripts/abi.ts. DO NOT EDIT.
package contractabi

import (
    _ "embed"
    "strings"
    "github.com/ethereum/go-ethereum/accounts/abi"
)

func parse(source string) abi.ABI {
    parsed, err := abi.JSON(strings.NewReader(source))
    if err != nil { panic(err) }
    return parsed
}

`;
  for (const record of [...records].sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const text = await readFile(
      join(directory, `contracts/abi/${record.name}.json`),
      "utf8",
    );
    if (createHash("sha256").update(text).digest("hex") !== record.abiSha256)
      throw new Error(`Canonical ABI hash differs: ${record.name}.`);
    const abi = JSON.parse(text);
    if (!Array.isArray(abi)) throw new Error(`Invalid ABI: ${record.name}.`);
    const symbol =
      record.name === "ERC20"
        ? "erc20"
        : record.name[0].toLowerCase() + record.name.slice(1);
    ts += `export const ${symbol}Abi = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;\n\n`;
    if (goNames.has(record.name)) {
      files.set(`${goDirectory}/${record.name}.json`, text);
      go += `//go:embed ${record.name}.json\nvar ${symbol}JSON string\n\nvar ${record.name} = parse(${symbol}JSON)\n\n`;
    }
  }
  files.set(`${tsDirectory}/index.ts`, ts);
  files.set(
    `${goDirectory}/abi.go`,
    execFileSync("gofmt", { input: go, encoding: "utf8" }),
  );
  return files;
}

export async function syncAbis(check: boolean, destination = root) {
  const files = await abiFiles();
  for (const directory of [goDirectory, tsDirectory]) {
    const existing = await readdir(join(destination, directory)).catch(
      () => [],
    );
    if (existing.some((name) => !files.has(`${directory}/${name}`)))
      throw new Error(
        `Stale generated ABI files in ${directory}; remove them explicitly.`,
      );
  }
  for (const [path, text] of files) {
    const absolute = join(destination, path);
    if (check) {
      if ((await readFile(absolute, "utf8").catch(() => undefined)) !== text)
        throw new Error(
          `Generated ABI differs: ${path}. Run bun scripts/abi.ts.`,
        );
    } else {
      await mkdir(dirname(absolute), { recursive: true });
      await writeFile(absolute, text);
    }
  }
}

if (import.meta.main) await syncAbis(process.argv.includes("--check"));
